(function(){'use strict';
const firebaseConfig={apiKey:"AIzaSyDhWlhYXPh34BuOf-kPYbGgYKVFew7fZ_g",authDomain:"projetoeclipse-2374b.firebaseapp.com",databaseURL:"https://projetoeclipse-2374b-default-rtdb.firebaseio.com",projectId:"projetoeclipse-2374b",storageBucket:"projetoeclipse-2374b.firebasestorage.app",messagingSenderId:"460740273909",appId:"1:460740273909:web:fb081ae806b15802a0c7bc",measurementId:"G-0806KRDLS2"};
let auth,db,storage,currentUser=null,currentProfile=null,setupStep=1,profilePhotoFile=null,coverPhotoFile=null,activeChatUid=null,activeChatRef=null;
const $=id=>document.getElementById(id); const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function show(id){document.querySelectorAll('.landing,.auth-screen,.setup-screen,.dashboard').forEach(x=>x.classList.add('hidden'));const el=id==='home'?document.querySelector('.landing'):$(id);if(el)el.classList.remove('hidden');scrollTo(0,0)}
function msg(el,text){if(el)el.textContent=text||''}
function firebaseMessage(e){const m={'auth/email-already-in-use':'Este e-mail já está cadastrado.','auth/invalid-email':'Digite um e-mail válido.','auth/weak-password':'A senha precisa ter pelo menos 6 caracteres.','auth/invalid-credential':'E-mail ou senha incorretos.','auth/user-not-found':'E-mail ou senha incorretos.','auth/network-request-failed':'Falha de conexão com o Firebase.'};return m[e?.code]||('Erro Firebase: '+(e?.message||'operação não concluída'))}
function initFirebase(){try{if(!window.firebase)return false;if(!firebase.apps.length)firebase.initializeApp(firebaseConfig);auth=firebase.auth();db=firebase.database();storage=firebase.storage();return true}catch(e){console.error(e);return false}}
function avatar(url,cls='avatar'){return url?`<span class="${cls}"><img src="${esc(url)}"></span>`:`<span class="${cls}">☾</span>`}
async function getProfile(uid){const s=await db.ref('profiles/'+uid).once('value');return s.val()||{uid}}
function closeMobile(){ $('sidebar')?.classList.remove('open'); $('mobileOverlay')?.classList.add('hidden') }
function bindNavigation(){
 document.querySelectorAll('[data-screen]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();show(b.dataset.screen)}));
 document.querySelectorAll('#mainNav [data-page],.top-icon').forEach(b=>b.addEventListener('click',()=>openPage(b.dataset.page)));
 $('topProfile').onclick=()=>openPage('profilePage'); $('mobileMenu').onclick=()=>{$('sidebar').classList.add('open');$('mobileOverlay').classList.remove('hidden')};$('mobileClose').onclick=closeMobile;$('mobileOverlay').onclick=closeMobile;
}
function openPage(id){document.querySelectorAll('.dash-page').forEach(p=>p.classList.add('hidden'));$(id)?.classList.remove('hidden');document.querySelectorAll('#mainNav [data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===id));closeMobile();if(id==='homePage')loadHome();if(id==='profilePage')renderOwnProfile();if(id==='friendsPage')loadFriends();if(id==='groupsPage')loadGroups();if(id==='notificationsPage')loadNotifications()}
function openDashboard(u){currentUser=u;$('welcome').textContent=u.displayName||'Meu perfil';$('topAvatar').outerHTML=avatar(currentProfile?.photoURL,'mini-avatar').replace('span class="mini-avatar"','span id="topAvatar" class="mini-avatar"');$('composerAvatar').outerHTML=avatar(currentProfile?.photoURL,'avatar').replace('span class="avatar"','span id="composerAvatar" class="avatar"');show('dashboard');openPage('homePage');loadChatFriends()}
async function checkAfterLogin(u){try{currentProfile=await getProfile(u.uid);if(currentProfile.setupCompleted===true)openDashboard(u);else openSetup(u)}catch(e){console.error(e);openDashboard(u)}}
function bindAuth(){$('loginForm').addEventListener('submit',async e=>{e.preventDefault();msg($('loginMsg'),'');try{await auth.signInWithEmailAndPassword($('loginEmail').value.trim(),$('loginPassword').value)}catch(err){msg($('loginMsg'),firebaseMessage(err))}});$('registerForm').addEventListener('submit',async e=>{e.preventDefault();msg($('registerMsg'),'');const p=$('regPassword').value;if(p!==$('regConfirm').value){msg($('registerMsg'),'As senhas não são iguais.');return}try{const c=await auth.createUserWithEmailAndPassword($('regEmail').value.trim().toLowerCase(),p);await c.user.updateProfile({displayName:$('regName').value.trim()});const uid=c.user.uid, name=$('regName').value.trim(), username=$('regUsername').value.trim().replace(/^@/,'').toLowerCase();await db.ref('users/'+uid).set({uid,name,username,createdAt:firebase.database.ServerValue.TIMESTAMP});await db.ref('profiles/'+uid).set({uid,displayName:name,username,birthDate:$('regBirth').value,bio:'',location:'',relationship:'',photoURL:'',coverURL:'',setupCompleted:false,createdAt:firebase.database.ServerValue.TIMESTAMP})}catch(err){msg($('registerMsg'),firebaseMessage(err))}})}
function openSetup(u){currentUser=u;setupStep=1;profilePhotoFile=null;coverPhotoFile=null;$('setupBio').value='';$('setupRelationship').value='';$('profilePhoto').value='';$('coverPhoto').value='';$('profilePreview').innerHTML='<span>☾</span>';$('coverPreview').innerHTML='<span>Foto de capa</span>';showSetupStep();show('profileSetup')}
function showSetupStep(){document.querySelectorAll('.setup-page').forEach(x=>x.classList.toggle('hidden',+x.dataset.step!==setupStep));$('setupStep').textContent=setupStep+' de 4';$('setupProgress').style.width=setupStep*25+'%';const t=['Vamos montar seu perfil.','Escolha sua foto de perfil.','Agora escolha sua foto de capa.','Como está seu relacionamento?'];const d=['Comece contando um pouco sobre você ou sobre sua personagem.','Essa será a imagem principal do seu perfil.','Sua capa ficará no topo da página do seu perfil.','Você poderá alterar essa informação depois.'];$('setupTitle').textContent=t[setupStep-1];$('setupDescription').textContent=d[setupStep-1];$('setupBack').style.visibility=setupStep===1?'hidden':'visible';$('setupNext').textContent=setupStep===4?'Concluir perfil':'Continuar'}
function bindSetup(){$('setupBio').addEventListener('input',()=>$('bioCount').textContent=$('setupBio').value.length);$('profilePhoto').addEventListener('change',e=>{profilePhotoFile=e.target.files[0]||null;if(profilePhotoFile)$('profilePreview').innerHTML=`<img src="${URL.createObjectURL(profilePhotoFile)}">`});$('coverPhoto').addEventListener('change',e=>{coverPhotoFile=e.target.files[0]||null;if(coverPhotoFile)$('coverPreview').innerHTML=`<img src="${URL.createObjectURL(coverPhotoFile)}">`});$('setupBack').onclick=()=>{if(setupStep>1){setupStep--;showSetupStep()}};$('setupNext').onclick=finishOrNext}
async function finishOrNext(){if(setupStep<4){setupStep++;showSetupStep();return}const b=$('setupNext');b.disabled=true;b.textContent='Salvando...';try{const uid=currentUser.uid,data={bio:$('setupBio').value.trim(),relationship:$('setupRelationship').value,setupCompleted:true,updatedAt:firebase.database.ServerValue.TIMESTAMP};if(profilePhotoFile){const r=storage.ref('profilePhotos/'+uid+'/profile');await r.put(profilePhotoFile);data.photoURL=await r.getDownloadURL()}if(coverPhotoFile){const r=storage.ref('coverPhotos/'+uid+'/cover');await r.put(coverPhotoFile);data.coverURL=await r.getDownloadURL()}await db.ref('profiles/'+uid).update(data);currentProfile=await getProfile(uid);openDashboard(currentUser)}catch(e){msg($('setupMessage'),firebaseMessage(e));b.disabled=false;b.textContent='Concluir perfil'}}
async function loadHome(){await loadFeed();await loadStories();await loadSuggestions();renderMiniProfile()}
function renderMiniProfile(){$('homeMiniProfile').innerHTML=`${avatar(currentProfile?.photoURL,'avatar')}<div><strong>${esc(currentProfile?.displayName||currentUser.displayName||'Perfil')}</strong><small>@${esc(currentProfile?.username||'')}</small></div>`}
async function loadFeed(){const s=await db.ref('posts').orderByChild('createdAt').limitToLast(40).once('value');const arr=[];s.forEach(x=>arr.push({id:x.key,...x.val()}));arr.reverse();if(!arr.length){$('feedList').innerHTML='<div class="card post"><p class="muted">Seu feed ainda está vazio. Comece publicando algo.</p></div>';return}const profiles={};for(const p of arr){profiles[p.uid]??=await getProfile(p.uid)}$('feedList').innerHTML=arr.map(p=>postHTML(p,profiles[p.uid]||{})).join('');await bindPostInteractions()}
function postHTML(p,pr){const liked=!!(p.reactions&&p.reactions[currentUser.uid]);const likes=p.likesCount||Object.keys(p.reactions||{}).length||0;const comments=p.commentsCount||0,shares=p.sharesCount||0;return `<article class="card post" data-post-id="${p.id}"><div class="post-head"><button class="post-author-link" data-profile-uid="${esc(p.uid)}">${avatar(pr.photoURL,'mini-avatar')}<span><strong>${esc(pr.displayName||'Usuário')}</strong><small>${p.createdAt?new Date(p.createdAt).toLocaleString('pt-BR'):''}</small></span></button></div>${p.text?`<div class="post-text">${esc(p.text)}</div>`:''}${p.imageURL?`<img class="post-image" src="${esc(p.imageURL)}">`:''}<div class="post-counts"><span>${likes} curtida${likes===1?'':'s'}</span><span>${comments} comentário${comments===1?'':'s'} · ${shares} compartilhamento${shares===1?'':'s'}</span></div><div class="post-actions"><button class="${liked?'liked':''}" data-like-post="${p.id}">♡ Curtir</button><button data-comment-post="${p.id}">◯ Comentar</button><button data-share-post="${p.id}">↗ Compartilhar</button></div><div class="comments-box" id="comments-${p.id}"></div></article>`}
async function bindPostInteractions(){document.querySelectorAll('[data-profile-uid]').forEach(b=>b.onclick=()=>viewProfile(b.dataset.profileUid));document.querySelectorAll('[data-like-post]').forEach(b=>b.onclick=()=>toggleLike(b.dataset.likePost));document.querySelectorAll('[data-comment-post]').forEach(b=>b.onclick=()=>toggleComments(b.dataset.commentPost));document.querySelectorAll('[data-share-post]').forEach(b=>b.onclick=()=>sharePost(b.dataset.sharePost))}
async function toggleLike(id){const ref=db.ref('posts/'+id),snap=await ref.once('value'),p=snap.val()||{},r=p.reactions||{};if(r[currentUser.uid]){delete r[currentUser.uid]}else{r[currentUser.uid]=true}await ref.update({reactions:r,likesCount:Object.keys(r).length});await loadFeed()}
async function toggleComments(id){const box=$('comments-'+id);if(box.classList.contains('loaded')){box.classList.toggle('open');return}const s=await db.ref('comments/'+id).orderByChild('createdAt').once('value');const a=[];s.forEach(x=>a.push({id:x.key,...x.val()}));box.innerHTML=`<div class="comments-list">${a.map(c=>`<div class="comment"><strong>${esc(c.name||'Usuário')}</strong><span>${esc(c.text)}</span></div>`).join('')}</div><form class="comment-form" data-comment-form="${id}"><input placeholder="Escreva um comentário..." required><button>Enviar</button></form>`;box.classList.add('loaded','open');box.querySelector('form').onsubmit=async e=>{e.preventDefault();const input=e.target.querySelector('input'),text=input.value.trim();if(!text)return;await db.ref('comments/'+id).push({uid:currentUser.uid,name:currentUser.displayName||currentProfile?.displayName||'Usuário',text,createdAt:firebase.database.ServerValue.TIMESTAMP});const p=await db.ref('posts/'+id).once('value');await db.ref('posts/'+id).update({commentsCount:(p.val()?.commentsCount||0)+1});input.value='';await toggleComments(id);box.classList.add('open')};}
async function sharePost(id){const p=await db.ref('posts/'+id).once('value');if(!p.exists())return;const v=p.val();await db.ref('shares/'+id).push({uid:currentUser.uid,createdAt:firebase.database.ServerValue.TIMESTAMP});await db.ref('posts/'+id).update({sharesCount:(v.sharesCount||0)+1});alert('Publicação compartilhada.');loadFeed()}
async function loadStories(){const s=await db.ref('statuses').orderByChild('createdAt').limitToLast(20).once('value');const arr=[];s.forEach(x=>arr.push({id:x.key,...x.val()}));arr.reverse();$('storiesList').innerHTML=arr.length?arr.map(x=>`<div class="story-card" data-story-id="${x.id}">${x.imageURL?`<img src="${esc(x.imageURL)}">`:''}<div class="story-avatar">☾</div><strong>${esc(x.displayName||'Amigo')}</strong></div>`).join(''):`<div class="muted">Seus amigos ainda não publicaram stories.</div>`}
async function loadSuggestions(){const s=await db.ref('profiles').limitToFirst(20).once('value');const arr=[];s.forEach(x=>{if(x.key!==currentUser.uid)arr.push({uid:x.key,...x.val()})});$('suggestionsList').innerHTML=arr.slice(0,5).map(x=>`<div class="suggestion"><button class="suggestion-person" data-profile-uid="${x.uid}">${avatar(x.photoURL,'mini-avatar')}<span><strong>${esc(x.displayName||'Usuário')}</strong><small>@${esc(x.username||'')}</small></span></button><button class="add-friend" data-add-friend="${x.uid}">Adicionar</button></div>`).join('')||'<p class="muted">Nenhuma sugestão encontrada.</p>';document.querySelectorAll('[data-add-friend]').forEach(b=>b.onclick=()=>sendFriendRequest(b.dataset.addFriend,b));document.querySelectorAll('.suggestion-person').forEach(b=>b.onclick=()=>viewProfile(b.dataset.profileUid))}
function bindFeed(){$('thinkingBtn').onclick=()=>openModal('postModal');$('composerPhotoBtn').onclick=()=>openModal('postModal');$('createStoryBtn').onclick=()=>openModal('storyModal');document.querySelectorAll('[data-close-modal]').forEach(b=>b.onclick=()=>b.closest('.modal').classList.add('hidden'));$('publishBtn').onclick=publishPost;$('publishStoryBtn').onclick=publishStory}
function openModal(id){$(id)?.classList.remove('hidden')}
async function publishPost(){const text=$('postText').value.trim(),file=$('postImage').files[0];if(!text&&!file){msg($('postMsg'),'Escreva algo ou escolha uma imagem.');return}const b=$('publishBtn');b.disabled=true;try{let imageURL='';if(file){const r=storage.ref('posts/'+currentUser.uid+'/'+Date.now()+'_'+file.name);await r.put(file);imageURL=await r.getDownloadURL()}await db.ref('posts').push({uid:currentUser.uid,text,imageURL,createdAt:firebase.database.ServerValue.TIMESTAMP,likesCount:0,commentsCount:0,sharesCount:0,reactions:{}});$('postText').value='';$('postImage').value='';$('postModal').classList.add('hidden');await loadFeed()}catch(e){msg($('postMsg'),firebaseMessage(e))}finally{b.disabled=false}}
async function publishStory(){const text=$('storyText').value.trim(),file=$('storyImage').files[0];if(!text&&!file){msg($('storyMsg'),'Escreva algo ou escolha uma imagem.');return}const b=$('publishStoryBtn');b.disabled=true;try{let imageURL='';if(file){const r=storage.ref('statuses/'+currentUser.uid+'/'+Date.now()+'_'+file.name);await r.put(file);imageURL=await r.getDownloadURL()}await db.ref('statuses').push({uid:currentUser.uid,displayName:currentUser.displayName||'Usuário',text,imageURL,createdAt:firebase.database.ServerValue.TIMESTAMP});$('storyText').value='';$('storyImage').value='';$('storyModal').classList.add('hidden');await loadStories()}catch(e){msg($('storyMsg'),firebaseMessage(e))}finally{b.disabled=false}}
async function renderOwnProfile(){const p=currentProfile||await getProfile(currentUser.uid);$('publicProfile').innerHTML=profileHTML(p,true);bindProfileButtons()}
async function viewProfile(uid){const p=await getProfile(uid);$('publicProfile').innerHTML=profileHTML(p,uid===currentUser.uid);bindProfileButtons();openPage('profilePage')}
function profileHTML(p,isOwn=false){return `<div class="profile-cover">${p.coverURL?`<img src="${esc(p.coverURL)}">`:''}</div><div class="profile-main"><div class="profile-head"><div class="profile-avatar-large">${p.photoURL?`<img src="${esc(p.photoURL)}">`:'☾'}</div><div class="profile-name"><h1>${esc(p.displayName||'Usuário')}</h1><p>@${esc(p.username||'')}</p></div><div class="profile-buttons">${isOwn?`<button class="profile-edit-btn" id="openProfileEdit">✎ Editar perfil</button>`:`<button class="primary" id="profileAddFriend" data-uid="${esc(p.uid)}">Adicionar como amigo</button><button class="secondary" id="profileMessage" data-uid="${esc(p.uid)}">Mensagem</button>`}</div></div><div class="profile-nav"><button class="active">Publicações</button><button>Sobre</button><button>Fotos</button><button>Amigos</button></div><div class="profile-info"><div class="card"><h3>Sobre</h3><div class="info-row"><b>Biografia:</b> ${esc(p.bio||'Ainda não adicionou uma biografia.')}</div><div class="info-row"><b>Mora em:</b> ${esc(p.location||'Não informado')}</div><div class="info-row"><b>Relacionamento:</b> ${esc(p.relationship||'Não informado')}</div></div><div class="card"><h3>Publicações</h3><div id="profilePosts"><p class="muted">Carregando...</p></div></div></div></div>`}
function bindProfileButtons(){const a=$('profileAddFriend'),m=$('profileMessage'),edit=$('openProfileEdit');if(a)a.onclick=()=>sendFriendRequest(a.dataset.uid,a);if(m)m.onclick=()=>openChat(m.dataset.uid);if(edit)edit.onclick=openProfileEditor;loadProfilePosts()}
async function loadProfilePosts(){const holder=$('profilePosts');if(!holder)return;const s=await db.ref('posts').orderByChild('uid').equalTo($('profileAddFriend')?.dataset.uid||currentUser.uid).once('value');const a=[];s.forEach(x=>a.push({id:x.key,...x.val()}));a.sort((x,y)=>(y.createdAt||0)-(x.createdAt||0));holder.innerHTML=a.length?a.slice(0,10).map(p=>`<div class="profile-post"><strong>${esc(p.text||'Publicação com mídia')}</strong>${p.imageURL?`<img src="${esc(p.imageURL)}">`:''}</div>`).join(''):'<p class="muted">Nenhuma publicação ainda.</p>'}
function openProfileEditor(){const p=currentProfile||{};$('profileEditPanel').classList.add('open');$('editProfileName').value=p.displayName||currentUser.displayName||'';$('editProfileUsername').value=p.username||'';$('editProfileBio').value=p.bio||'';$('editProfileLocation').value=p.location||'';$('editProfileRelationship').value=p.relationship||''}
async function saveProfileEdit(){const b=$('saveProfileEdit');b.disabled=true;try{const uid=currentUser.uid,data={displayName:$('editProfileName').value.trim(),username:$('editProfileUsername').value.trim().replace(/^@/,''),bio:$('editProfileBio').value.trim(),location:$('editProfileLocation').value.trim(),relationship:$('editProfileRelationship').value,updatedAt:firebase.database.ServerValue.TIMESTAMP};const pf=$('editProfilePhoto').files[0],cf=$('editProfileCover').files[0];if(pf){const r=storage.ref('profilePhotos/'+uid+'/profile');await r.put(pf);data.photoURL=await r.getDownloadURL()}if(cf){const r=storage.ref('coverPhotos/'+uid+'/cover');await r.put(cf);data.coverURL=await r.getDownloadURL()}await db.ref('profiles/'+uid).update(data);await currentUser.updateProfile({displayName:data.displayName||currentUser.displayName});currentProfile=await getProfile(uid);$('profileEditPanel').classList.remove('open');renderOwnProfile();$('topAvatar').outerHTML=avatar(currentProfile.photoURL,'mini-avatar').replace('span class="mini-avatar"','span id="topAvatar" class="mini-avatar"');$('composerAvatar').outerHTML=avatar(currentProfile.photoURL,'avatar').replace('span class="avatar"','span id="composerAvatar" class="avatar"')}catch(e){msg($('profileEditMsg'),firebaseMessage(e))}finally{b.disabled=false}}
async function sendFriendRequest(uid,button){if(!uid||uid===currentUser.uid)return;try{const existing=await db.ref('friendRequests/'+uid+'/'+currentUser.uid).once('value');if(existing.exists()){button.textContent='Solicitação enviada';button.disabled=true;return}await db.ref('friendRequests/'+uid+'/'+currentUser.uid).set({uid:currentUser.uid,name:currentUser.displayName||'',createdAt:firebase.database.ServerValue.TIMESTAMP});await db.ref('notifications/'+uid).push({type:'friend_request',fromUid:currentUser.uid,fromName:currentUser.displayName||'',createdAt:firebase.database.ServerValue.TIMESTAMP,read:false});button.textContent='Solicitação enviada';button.disabled=true}catch(e){alert(firebaseMessage(e))}}
async function loadFriends(){const req=await db.ref('friendRequests/'+currentUser.uid).once('value'),r=[];req.forEach(x=>r.push({uid:x.key,...x.val()}));$('friendRequestsList').innerHTML=r.length?'<h3>Solicitações</h3>'+r.map(x=>`<div class="list-item"><div class="list-main">${avatar('','mini-avatar')}<div><strong>${esc(x.name||'Usuário')}</strong><small>Quer ser seu amigo.</small></div></div><button class="primary" data-accept="${x.uid}">Aceitar</button></div>`).join(''):'<p class="muted">Nenhuma solicitação de amizade.</p>';document.querySelectorAll('[data-accept]').forEach(b=>b.onclick=()=>acceptFriend(b.dataset.accept));const fs=await db.ref('friendships/'+currentUser.uid).once('value'),ids=[];fs.forEach(x=>ids.push(x.key));$('friendsList').innerHTML='<h3>Seus amigos</h3>'+(ids.length?'<div class="list">'+(await Promise.all(ids.map(async id=>{const p=await getProfile(id);return `<div class="list-item"><button class="suggestion-person" data-profile-uid="${id}">${avatar(p.photoURL,'mini-avatar')}<strong>${esc(p.displayName||'Usuário')}</strong></button><button class="secondary" data-message="${id}">Mensagem</button></div>`}))).join('')+'</div>':'<p class="muted">Você ainda não tem amigos.</p>');document.querySelectorAll('[data-message]').forEach(b=>b.onclick=()=>openChat(b.dataset.message));document.querySelectorAll('[data-profile-uid]').forEach(b=>b.onclick=()=>viewProfile(b.dataset.profileUid))}
async function acceptFriend(uid){const updates={};updates['friendships/'+currentUser.uid+'/'+uid]=true;updates['friendships/'+uid+'/'+currentUser.uid]=true;updates['friendRequests/'+currentUser.uid+'/'+uid]=null;await db.ref().update(updates);loadFriends()}
async function loadNotifications(){const s=await db.ref('notifications/'+currentUser.uid).orderByChild('createdAt').limitToLast(30).once('value'),a=[];s.forEach(x=>a.push(x.val()));a.reverse();$('notificationsList').innerHTML=a.length?a.map(x=>`<div class="list-item">${esc(x.fromName||'Alguém')} ${x.type==='friend_request'?'enviou uma solicitação de amizade.':'interagiu com você.'}</div>`).join(''):'<p class="muted">Nenhuma notificação.</p>'}
async function loadGroups(){const s=await db.ref('groups').orderByChild('createdAt').limitToLast(20).once('value'),a=[];s.forEach(x=>a.push({id:x.key,...x.val()}));a.reverse();$('groupsList').innerHTML=a.length?a.map(g=>`<div class="list-item"><div><strong>${esc(g.name)}</strong><small>${esc(g.description||'')}</small></div></div>`).join(''):'<p class="muted">Nenhum grupo criado ainda.</p>'}
function bindGroups(){$('groupForm').addEventListener('submit',async e=>{e.preventDefault();try{const ref=db.ref('groups').push();await ref.set({name:$('groupName').value.trim(),description:$('groupDescription').value.trim(),ownerUid:currentUser.uid,createdAt:firebase.database.ServerValue.TIMESTAMP});await db.ref('groupMembers/'+ref.key+'/'+currentUser.uid).set({role:'owner'});$('groupName').value='';$('groupDescription').value='';msg($('groupMsg'),'Grupo criado com sucesso.');loadGroups()}catch(err){msg($('groupMsg'),firebaseMessage(err))}})}
function bindPrivacy(){$('privacyForm').addEventListener('submit',async e=>{e.preventDefault();try{await db.ref('privacySettings/'+currentUser.uid).set({friends:$('privacyFriends').value,find:$('privacyFind').value,requests:$('privacyRequests').value});msg($('privacyMsg'),'Privacidade salva.')}catch(err){msg($('privacyMsg'),firebaseMessage(err))}})}
async function discover(){const q=$('discoverInput').value.trim().toLowerCase(),s=await db.ref('profiles').once('value'),a=[];s.forEach(x=>{const p=x.val()||{};if(x.key!==currentUser.uid&&(!q||(p.displayName||'').toLowerCase().includes(q)||(p.username||'').toLowerCase().includes(q)))a.push({uid:x.key,...p})});$('discoverResults').innerHTML=a.map(p=>`<div class="list-item"><button class="suggestion-person" data-profile-uid="${p.uid}">${avatar(p.photoURL,'mini-avatar')}<div><strong>${esc(p.displayName||'Usuário')}</strong><small>@${esc(p.username||'')}</small></div></button><div><button class="primary" data-view-profile="${p.uid}">Ver perfil</button><button class="secondary" data-discover-add="${p.uid}">Adicionar</button></div></div>`).join('')||'<p class="muted">Nenhum perfil encontrado.</p>';document.querySelectorAll('[data-view-profile]').forEach(b=>b.onclick=()=>viewProfile(b.dataset.viewProfile));document.querySelectorAll('[data-discover-add]').forEach(b=>b.onclick=()=>sendFriendRequest(b.dataset.discoverAdd,b));document.querySelectorAll('[data-profile-uid]').forEach(b=>b.onclick=()=>viewProfile(b.dataset.profileUid))}
function bindDiscover(){$('discoverBtn').onclick=discover;$('globalSearch').addEventListener('keydown',e=>{if(e.key==='Enter'){openPage('discoverPage');$('discoverInput').value=e.target.value;discover()}})}
async function loadChatFriends(){const bar=$('chatFriendsBar');if(!bar)return;const fs=await db.ref('friendships/'+currentUser.uid).once('value'),ids=[];fs.forEach(x=>ids.push(x.key));const profiles=await Promise.all(ids.slice(0,8).map(getProfile));bar.innerHTML=profiles.map(p=>`<button class="chat-friend" data-chat-user="${p.uid}">${avatar(p.photoURL,'mini-avatar')}<span>${esc(p.displayName||'Usuário')}</span></button>`).join('')||'<span class="muted">Adicione amigos para conversar.</span>';bar.querySelectorAll('[data-chat-user]').forEach(b=>b.onclick=()=>openChat(b.dataset.chatUser))}
async function openChat(uid){if(!uid||uid===currentUser.uid)return;activeChatUid=uid;const p=await getProfile(uid);$('chatName').textContent=p.displayName||'Usuário';$('chatStatus').textContent='@'+(p.username||'');const old=$('chatAvatar');if(old)old.outerHTML=avatar(p.photoURL,'mini-avatar').replace('span class="mini-avatar"','span id="chatAvatar" class="mini-avatar"');$('messageDock').classList.remove('hidden');const key=[currentUser.uid,uid].sort().join('_');if(activeChatRef)activeChatRef.off();activeChatRef=db.ref('messages/'+key);activeChatRef.on('value',s=>{const a=[];s.forEach(x=>a.push(x.val()));a.sort((x,y)=>(x.createdAt||0)-(y.createdAt||0));$('chatMessages').innerHTML=a.map(x=>`<div class="bubble ${x.uid===currentUser.uid?'mine':''}">${esc(x.text)}</div>`).join('');$('chatMessages').scrollTop=$('chatMessages').scrollHeight})}
function bindChat(){$('openChatBar').onclick=()=>{$('chatFriendsBar').classList.toggle('hidden');loadChatFriends()};$('closeChat').onclick=()=>{$('messageDock').classList.add('hidden');if(activeChatRef)activeChatRef.off();activeChatRef=null};$('chatForm').addEventListener('submit',async e=>{e.preventDefault();const t=$('chatText').value.trim();if(!t||!activeChatUid)return;const key=[currentUser.uid,activeChatUid].sort().join('_');await db.ref('messages/'+key).push({uid:currentUser.uid,text:t,createdAt:firebase.database.ServerValue.TIMESTAMP});$('chatText').value=''})}
document.addEventListener('click',e=>{if(e.target.closest('#saveProfileEdit'))saveProfileEdit();if(e.target.closest('#cancelProfileEdit'))$('profileEditPanel').classList.remove('open')});
document.addEventListener('DOMContentLoaded',()=>{bindNavigation();bindAuth();bindSetup();bindFeed();bindChat();bindGroups();bindPrivacy();bindDiscover();if(initFirebase())auth.onAuthStateChanged(u=>{if(u)checkAfterLogin(u);else show('home')});else $('loginMsg').textContent='Firebase não foi carregado.'});
})();
